### ISSUE TITLE
Migrate wiki pages

### ISSUE THREAD

**Issue by vogella** [eclipse-swtbot/org.eclipse.swtbot#5]
I can help migrate your wike pages to Markdown.

What pages should be migrated?

**Comment by PatrickTasse** [comment]
Thanks for the offer! I believe all the pages were converted to markdown. I tried to fix all the links but there might be some that are still wrong. Feel free to fix any problem you find, do you have required permissions?

https://github.com/eclipse-swtbot/org.eclipse.swtbot/wiki

**Comment by PatrickTasse** [comment]
@vogella Are there any pages still needing migration, or can this issue be closed?

**Comment by vogella** [comment]
Ah, sorry, I assumed you closed already
